new wine + proton

diff --git a/scripts/termux-box b/scripts/termux-box
--- a/scripts/termux-box
+++ b/scripts/termux-box
@@ -4,18 +4,24 @@ cd $HOME/termux-box
 
 if [ ! -e ubuntu-fs/opt/wine ]; then
     echo "Select which Wine to download"
-    echo "1) 8.2 staging"
-    echo "2) 8.14 ge-custom"
+    echo "1) 8.16 staging"
+    echo "2) 8.17 ge-custom"
+    echo "3) 8.0 proton"
     read opcode
     case $opcode in
     1)
-    if ! wget -q --show-progress https://github.com/Kron4ek/Wine-Builds/releases/download/8.2/wine-8.2-staging-amd64.tar.xz -O ubuntu-fs/opt/wine.tar.xz; then
+    if ! wget -q --show-progress https://github.com/Kron4ek/Wine-Builds/releases/download/8.16/wine-8.16-staging-amd64.tar.xz -O ubuntu-fs/opt/wine.tar.xz; then
     echo "Download failed, restart termux-box"
     exit
     fi
     ;;
     2)
-    if ! wget -q --show-progress https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-14/wine-lutris-GE-Proton8-14-x86_64.tar.xz -O ubuntu-fs/opt/wine.tar.xz; then
+    if ! wget -q --show-progress https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-17/wine-lutris-GE-Proton8-17-x86_64.tar.xz -O ubuntu-fs/opt/wine.tar.xz; then
+    echo "Download failed, restart termux-box"
+    exit
+    fi
+    3)
+    if ! wget -q --show-progress https://github.com/Kron4ek/Wine-Builds/releases/download/proton-exp-8.0/wine-proton-exp-8.0-amd64.tar.xz -O ubuntu-fs/opt/wine.tar.xz; then
     echo "Download failed, restart termux-box"
     exit
     fi
